#!/usr/bin/env python3
"""Regenerate docs/sdl/INDEX.md from cycle metadata.

Replaces the agent-performed step of sdl-review §6. Deterministic: rows are
sorted by folder name (date-prefixed slugs sort chronologically), summaries
come from each cycle's own files. Run from the root of the repo being
governed:

    python3 <governance>/lib/gen_index.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HEADER = """# SDL Cycle Index

<!-- Generated by gen_index.py — edit the cycle files, not this table. -->

| Slug | Branch | PR | Status | Created | Summary |
|------|--------|----|--------|---------|---------|
"""


def meta_field(text: str, key: str) -> str:
    m = re.search(rf"^{key}:[ \t]*(.*?)[ \t]*$", text, re.MULTILINE)
    return m.group(1) if m else ""


def section(text: str, title: str) -> list[str]:
    """Content lines of a '## <title>' section, comments stripped."""
    lines: list[str] = []
    in_section = in_comment = False
    for line in text.splitlines():
        if line.startswith("## "):
            in_section = line[3:].strip().lower() == title.lower()
            continue
        if not in_section:
            continue
        s = line.strip()
        if in_comment:
            in_comment = "-->" not in s
            continue
        if s.startswith("<!--"):
            in_comment = "-->" not in s
            continue
        if s:
            lines.append(s)
    return lines


def first_sentence(line: str) -> str:
    return re.split(r"(?<=[.!?])\s+", line)[0]


def dep_summary(record: Path) -> str:
    """Build 'Dependency update: pkg from→to, …' from the Updates table."""
    bumps = []
    for row in section(record.read_text(encoding="utf-8", errors="replace"), "Updates"):
        cells = [c.strip() for c in row.strip("|").split("|")]
        if len(cells) < 3 or cells[0].lower() == "package" or set(cells[0]) <= {"-", ":", " "}:
            continue
        if cells[0]:
            bumps.append(f"{cells[0]} {cells[1]}→{cells[2]}")
    return "Dependency update: " + ", ".join(bumps) if bumps else "Dependency update."


def cycle_summary(cycle: Path, cycle_class: str) -> str:
    if cycle_class == "dependency-update":
        record = cycle / "dep-update.md"
        return dep_summary(record) if record.is_file() else ""
    req = cycle / "01-requirements.md"
    if not req.is_file():
        return ""
    lines = section(req.read_text(encoding="utf-8", errors="replace"), "Summary")
    return first_sentence(lines[0]) if lines else ""


def cell(text: str) -> str:
    return text.replace("|", "\\|") or "—"


def generate(repo: Path) -> str:
    sdl = repo / "docs" / "sdl"
    rows = []
    for meta in sorted(sdl.glob("*/.sdl-meta.yml")):
        cycle = meta.parent
        text = meta.read_text(encoding="utf-8", errors="replace")
        pr = meta_field(text, "pr")
        row = (
            meta_field(text, "slug") or cycle.name,
            meta_field(text, "branch"),
            "—" if pr in ("", "null") else pr,
            meta_field(text, "status"),
            meta_field(text, "created"),
            cycle_summary(cycle, meta_field(text, "class")),
        )
        rows.append("| " + " | ".join(cell(c) for c in row) + " |")
    return HEADER + "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/sdl/INDEX.md.")
    parser.add_argument("--repo", default=".", help="repo root")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if INDEX.md is out of date instead of writing")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    sdl = repo / "docs" / "sdl"
    if not sdl.is_dir():
        print(f"{repo} has no docs/sdl/ — not an SDL-governed repo", file=sys.stderr)
        return 1
    content = generate(repo)
    index = sdl / "INDEX.md"
    if args.check:
        current = index.read_text(encoding="utf-8") if index.is_file() else ""
        if current != content:
            print("docs/sdl/INDEX.md is out of date — run gen_index.py", file=sys.stderr)
            return 1
        print("docs/sdl/INDEX.md is current")
        return 0
    index.write_text(content, encoding="utf-8")
    print(index.relative_to(repo))
    return 0


if __name__ == "__main__":
    sys.exit(main())
