#!/usr/bin/env python3
"""Tests for the INDEX.md generator. Stdlib only — run with:

    python3 lib/test_gen_index.py       # or: python3 -m unittest -v
"""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_index as gi  # noqa: E402

META = """slug: {slug}
branch: {branch}
created: {created}
pr: {pr}
status: {status}
related_cycles: []
carry_forward: []
"""

REQ = """# 01 — Requirements

## Summary

{summary}

## Scope

Not the summary.
"""


class Generate(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.repo = Path(self.tmp.name)
        self.sdl = self.repo / "docs" / "sdl"
        self.sdl.mkdir(parents=True)

    def add_cycle(self, slug, summary="A change.", pr="null", status="in-progress",
                  cycle_class=None):
        cycle = self.sdl / slug
        cycle.mkdir()
        meta = META.format(slug=slug, branch=slug[11:], created=slug[:10],
                           pr=pr, status=status)
        if cycle_class:
            meta += f"class: {cycle_class}\n"
        (cycle / ".sdl-meta.yml").write_text(meta, encoding="utf-8")
        if cycle_class != "dependency-update":
            (cycle / "01-requirements.md").write_text(
                REQ.format(summary=summary), encoding="utf-8")
        return cycle

    def rows(self):
        return [ln for ln in gi.generate(self.repo).splitlines()
                if ln.startswith("| 2")]

    def test_row_content_and_order(self):
        self.add_cycle("2026-07-09-bbb", summary="Second thing.", pr="12", status="merged")
        self.add_cycle("2026-06-10-aaa", summary="First thing.")
        rows = self.rows()
        self.assertEqual(len(rows), 2)
        self.assertEqual(
            rows[0],
            "| 2026-06-10-aaa | aaa | — | in-progress | 2026-06-10 | First thing. |")
        self.assertEqual(
            rows[1],
            "| 2026-07-09-bbb | bbb | 12 | merged | 2026-07-09 | Second thing. |")

    def test_summary_is_first_sentence_only(self):
        self.add_cycle("2026-07-09-aaa",
                       summary="Do the thing. Then lots of detail follows.")
        self.assertIn("| Do the thing. |", self.rows()[0])

    def test_pipes_in_summary_are_escaped(self):
        self.add_cycle("2026-07-09-aaa", summary="Uses a | pipe.")
        row = self.rows()[0]
        self.assertIn("Uses a \\| pipe.", row)
        # The row still parses to six columns: five unescaped separators.
        self.assertEqual(row.count(" | "), 5)

    def test_comments_in_summary_section_are_skipped(self):
        self.add_cycle("2026-07-09-aaa",
                       summary="<!-- template hint -->\n\nReal summary.")
        self.assertIn("| Real summary. |", self.rows()[0])

    def test_dep_update_cycle_summary_from_table(self):
        cycle = self.add_cycle("2026-07-09-dep", cycle_class="dependency-update")
        (cycle / "dep-update.md").write_text(
            "## Updates\n\n"
            "| package | from | to | source |\n"
            "|---------|------|----|--------|\n"
            "| actions/checkout | v6.0.3 | v7.0.0 | dependabot |\n",
            encoding="utf-8")
        self.assertIn("| Dependency update: actions/checkout v6.0.3→v7.0.0 |",
                      self.rows()[0])

    def test_missing_fields_render_as_dash(self):
        cycle = self.sdl / "2026-07-09-bare"
        cycle.mkdir()
        (cycle / ".sdl-meta.yml").write_text("slug: 2026-07-09-bare\n", encoding="utf-8")
        row = self.rows()[0]
        self.assertEqual(row, "| 2026-07-09-bare | — | — | — | — | — |")

    def test_bare_pr_key_does_not_swallow_next_line(self):
        # Early cycles wrote "pr:" with no value; the PR cell must render as
        # a dash, not capture the following "status:" line.
        cycle = self.sdl / "2026-06-10-old"
        cycle.mkdir()
        (cycle / ".sdl-meta.yml").write_text(
            "slug: 2026-06-10-old\nbranch: old\ncreated: 2026-06-10\n"
            "pr:\nstatus: merged\n", encoding="utf-8")
        self.assertEqual(
            self.rows()[0],
            "| 2026-06-10-old | old | — | merged | 2026-06-10 | — |")

    def test_generated_header_and_marker(self):
        self.add_cycle("2026-07-09-aaa")
        out = gi.generate(self.repo)
        self.assertTrue(out.startswith("# SDL Cycle Index\n"))
        self.assertIn("Generated by gen_index.py", out)


if __name__ == "__main__":
    unittest.main(verbosity=2)
